FROM grafana/alloy:v1.20.1

COPY alloy/config.alloy /etc/alloy/config.alloy

USER alloy

EXPOSE 4317 12345

CMD ["run", "--server.http.listen-addr=0.0.0.0:12345", "--storage.path=/var/lib/alloy/data", "--disable-reporting", "/etc/alloy/config.alloy"]
