global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090

  - job_name: shortscale-api
    metrics_path: /metrics
    dns_sd_configs:
      - names:
          - api
        type: A
        port: 8080
        refresh_interval: 5s

  - job_name: shortscale-analytics-consumer
    metrics_path: /metrics
    static_configs:
      - targets:
          - analytics-consumer:9091
